# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ka-w9qmGNY_6pvsIpHtC4WdRsSi_Qf-T
"""

from flask import Flask, request, render_template
import pickle
import numpy as np

app = Flask(__name__, template_folder='template')

filename = 'final_model_Kmean_clustring.pkl'
model = pickle.load(open(filename, 'rb'))

@app.route("/")
def index():
    return render_template("index.html")

@app.route("/submit", methods=["GET", "POST"])
def predict():
    if request.method == "POST":
        OpenPrice = request.form['Open']
        ClosePrice = request.form['Close']
        result = np.array([[OpenPrice, ClosePrice]])
        prediction = model.predict(result)

        if prediction == 0:
            display = "Stocks belongs to Group 1"
        elif prediction == 1:
            display = "Stocks belongs to Group 2"
        elif prediction == 2:
            display = "Stocks belongs to Group 3"
        elif prediction == 3:
            display = "Stocks belongs to Group 4"
        else:
            display = "Stocks belongs to Group 5"

    return render_template("submit.html", n=display)

if __name__ == "__main__":
    app.run(debug=True)